apiVersion: apps.tanzu.vmware.com/v1
kind: ContainerApp
metadata:
  name: spring-music
spec:
  build:
    buildpacks: {}
    nonSecretEnv:
    - name: BP_JVM_VERSION
      value: "17"
    path: ../..
  ports:
  - name: main
    port: 8080
